# Site settings
full-title: Join Us in Colorful Colorado
title1: Join Us In
title2: COLORFUL<br>COLORADO
email: ken.caron+kenandjackie@gmail.com
url: https://example.github.io
description: "Jacqualyn Blizzard & Kenneth Caron<br>are celebrating their wedding on<br>Sunday, July 9th."

# Color settings (hex-codes without the leading hash-tag)
color:
  background: '#2a363b'
  main-background: '#0d3a1d'
  top-nav-background: 'rgba(42, 54, 59, 0.6)'
  links: '#5cd0ff'
  links-hover: '#eee'


# Footer settings
footer: Our Footer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: https://twitter.com/SBootstrap
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
